<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE menu [
<!ELEMENT menu (main,skills,hobbies,achievements,projects,contact) >
<!ELEMENT main (name,secondname)>
<!ATTLIST main university CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT secondname (#PCDATA)>
<!ELEMENT skills (MobileDev,WebDev)>
<!ELEMENT MobileDev (#PCDATA)>
<!ELEMENT WebDev (#PCDATA)>
<!ELEMENT hobbies (active,inactive)>
<!ELEMENT active (#PCDATA)>
<!ELEMENT inactive (#PCDATA)>
<!ELEMENT achievements (sport,studies)>
<!ELEMENT sport (#PCDATA)>
<!ELEMENT studies (#PCDATA)>
<!ELEMENT projects (mobileApp?)>
<!ELEMENT mobileApp (#PCDATA)>
<!ELEMENT contact (vk,linkedIn)>
<!ELEMENT vk (#PCDATA)>
<!ELEMENT linkedIn (#PCDATA)>
]>

<menu>
	<main university="GrSU">
		<name>Andrey</name>
		<secondname>Molochko</secondname>
	</main>
	<skills>
		<MobileDev>Android</MobileDev>
		<WebDev>web-programmer</WebDev>
	</skills>
	<hobbies>
		<active>sport</active>
		<inactive>reading</inactive>
	</hobbies>
	<achievements>
		<sport>Achievements in sport</sport>
		<studies>Achievements in studies</studies>
	</achievements>
	<projects>
		<mobileApp>Progress Diary</mobileApp>
	</projects>
	<contact>
		<vk>link vk</vk>
		<linkedIn>link linkedIn</linkedIn>		
	</contact>
</menu>
